/*
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.mule


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MuLEStandaloneSetup extends MuLEStandaloneSetupGenerated {

	def static void doSetup() {
		new MuLEStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
