/*
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.parser.antlr;

import com.google.inject.Inject;
import de.ubt.ai1.mule.parser.antlr.internal.InternalMuLEParser;
import de.ubt.ai1.mule.services.MuLEGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MuLEParser extends AbstractAntlrParser {

	@Inject
	private MuLEGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMuLEParser createParser(XtextTokenStream stream) {
		return new InternalMuLEParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CompilationUnit";
	}

	public MuLEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MuLEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
