/*
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.mule.ide

import com.google.inject.Guice
import de.ubt.ai1.mule.MuLERuntimeModule
import de.ubt.ai1.mule.MuLEStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MuLEIdeSetup extends MuLEStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MuLERuntimeModule, new MuLEIdeModule))
	}
	
}
