/**
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.muLE.impl;

import de.ubt.ai1.mule.muLE.Dereference;
import de.ubt.ai1.mule.muLE.MuLEPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dereference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DereferenceImpl extends SymbolRefAccessModifierImpl implements Dereference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DereferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MuLEPackage.Literals.DEREFERENCE;
  }

} //DereferenceImpl
