/**
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.muLE;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dereference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.ubt.ai1.mule.muLE.MuLEPackage#getDereference()
 * @model
 * @generated
 */
public interface Dereference extends SymbolRefAccessModifier
{
} // Dereference
