/**
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.muLE;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.ubt.ai1.mule.muLE.MuLEPackage#getEnumerationValue()
 * @model
 * @generated
 */
public interface EnumerationValue extends NamedElement
{
} // EnumerationValue
