/**
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.muLE;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Invocation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.mule.muLE.OperationInvocation#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see de.ubt.ai1.mule.muLE.MuLEPackage#getOperationInvocation()
 * @model
 * @generated
 */
public interface OperationInvocation extends SymbolRefAccessModifier
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link de.ubt.ai1.mule.muLE.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see de.ubt.ai1.mule.muLE.MuLEPackage#getOperationInvocation_Params()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getParams();

} // OperationInvocation
