/**
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.muLE;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.mule.muLE.OperationType#getParamTypes <em>Param Types</em>}</li>
 *   <li>{@link de.ubt.ai1.mule.muLE.OperationType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see de.ubt.ai1.mule.muLE.MuLEPackage#getOperationType()
 * @model
 * @generated
 */
public interface OperationType extends DataType
{
  /**
   * Returns the value of the '<em><b>Param Types</b></em>' containment reference list.
   * The list contents are of type {@link de.ubt.ai1.mule.muLE.DataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Types</em>' containment reference list.
   * @see de.ubt.ai1.mule.muLE.MuLEPackage#getOperationType_ParamTypes()
   * @model containment="true"
   * @generated
   */
  EList<DataType> getParamTypes();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(DataType)
   * @see de.ubt.ai1.mule.muLE.MuLEPackage#getOperationType_Type()
   * @model containment="true"
   * @generated
   */
  DataType getType();

  /**
   * Sets the value of the '{@link de.ubt.ai1.mule.muLE.OperationType#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(DataType value);

} // OperationType
