/**
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.muLE;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Super Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.mule.muLE.SuperExpression#getMemberCall <em>Member Call</em>}</li>
 * </ul>
 *
 * @see de.ubt.ai1.mule.muLE.MuLEPackage#getSuperExpression()
 * @model
 * @generated
 */
public interface SuperExpression extends AssignmentOrOperationCall, Expression
{
  /**
   * Returns the value of the '<em><b>Member Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member Call</em>' containment reference.
   * @see #setMemberCall(SymbolReference)
   * @see de.ubt.ai1.mule.muLE.MuLEPackage#getSuperExpression_MemberCall()
   * @model containment="true"
   * @generated
   */
  SymbolReference getMemberCall();

  /**
   * Sets the value of the '{@link de.ubt.ai1.mule.muLE.SuperExpression#getMemberCall <em>Member Call</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Member Call</em>' containment reference.
   * @see #getMemberCall()
   * @generated
   */
  void setMemberCall(SymbolReference value);

} // SuperExpression
