/**
 * generated by Xtext 2.19.0
 */
package de.ubt.ai1.mule.muLE;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Symbol Ref Access Modifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.mule.muLE.SymbolRefAccessModifier#getAccessModifier <em>Access Modifier</em>}</li>
 * </ul>
 *
 * @see de.ubt.ai1.mule.muLE.MuLEPackage#getSymbolRefAccessModifier()
 * @model
 * @generated
 */
public interface SymbolRefAccessModifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Access Modifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access Modifier</em>' containment reference.
   * @see #setAccessModifier(SymbolRefAccessModifier)
   * @see de.ubt.ai1.mule.muLE.MuLEPackage#getSymbolRefAccessModifier_AccessModifier()
   * @model containment="true"
   * @generated
   */
  SymbolRefAccessModifier getAccessModifier();

  /**
   * Sets the value of the '{@link de.ubt.ai1.mule.muLE.SymbolRefAccessModifier#getAccessModifier <em>Access Modifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Access Modifier</em>' containment reference.
   * @see #getAccessModifier()
   * @generated
   */
  void setAccessModifier(SymbolRefAccessModifier value);

} // SymbolRefAccessModifier
